name: AutoPkg run

on:
  workflow_dispatch: # manually triggered
    inputs:
      recipe:
        description: Recipe to Run (optional)
        required: false

jobs:
  AutoPkg:
    runs-on: macos-latest
    timeout-minutes: 150 # Keeps your builds from running too long
    env:
      MUNKI_REPOSITORY: joncrain/munki_repo
    steps:
    - name: Checkout AutoPkg recipes (this repo)
      uses: actions/checkout@v3

    - name: Checkout your Munki LFS repo
      uses: actions/checkout@v3
      with:
        repository: ${{ env.MUNKI_REPOSITORY }}
        token: ${{ secrets.MUNKI_GITHUB_TOKEN }}
        path: munki_repo

    - name: Install Munki
      uses: joncrain/macos-pkg-install@10269cf9fd6482d0b58f42edb3832e030d651f92
      with:
        pkg_url: https://github.com/munki/munki/releases/download/v${{ vars.MUNKI_VERSION }}/munkitools-${{ vars.MUNKI_EXPLICIT_VERSION }}.pkg

    - name: Install AutoPkg
      uses: joncrain/macos-pkg-install@10269cf9fd6482d0b58f42edb3832e030d651f92
      with:
        pkg_url: https://github.com/autopkg/autopkg/releases/download/v${{ vars.AUTOPKG_VERSION }}/autopkg-${{ vars.AUTOPKG_VERSION }}.pkg

    - name: Configure AutoPkg
      run: |
        defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "$GITHUB_WORKSPACE"/overrides/
        defaults write com.github.autopkg RECIPE_REPO_DIR "$GITHUB_WORKSPACE"/repos/
        defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool YES
        defaults write com.github.autopkg MUNKI_REPO "$GITHUB_WORKSPACE"/munki_repo
        defaults write com.github.autopkg GITHUB_TOKEN "${{ secrets.MUNKI_GITHUB_TOKEN }}"
        git config --global user.name "runner"
        git config --global user.email "runner@githubactions.local"

    - name: Configure AutoPkg Repos
      run: |
        for repo in $(cat repo_list.txt); do autopkg repo-add "$repo"; done

    - name: Update AutoPkg Repos
      run: autopkg repo-update all

    - name: Run makecatalogs
      run: /usr/local/munki/makecatalogs munki_repo -s

    - name: Run AutoPkg
      run: |
        pip3 install -r requirements.txt
        python3 autopkg_tools.py -l recipe_list.json
      env:
        RECIPE: ${{ github.event.inputs.recipe }}
        SLACK_WEBHOOK_TOKEN: ${{ secrets.autopkg_slack_token }}
        MUNKI_REPOSITORY: ${{ env.MUNKI_REPOSITORY }}
        GH_TOKEN: ${{ secrets.MUNKI_GITHUB_TOKEN }}
