name: AutoPkg run

on:
  workflow_dispatch: # manually triggered
    inputs:
      recipe:
        description: Recipe to Run (optional)
        required: false

jobs:
  AutoPkg:
    runs-on: macos-latest
    timeout-minutes: 10 # Keeps your builds from running too long
    steps:
    - name: Checkout AutoPkg recipes (this repo)
      uses: actions/checkout@v3

    - name: Cache Munki Pkg
      uses: actions/cache@v3
      id: munki-pkg-cache
      with:
        path: ${{ github.workspace }}/munkitools.pkg
        key: ${{ runner.os }}-munki-pkg-${{ vars.MUNKI_EXPLICIT_VERSION }}

    - name: Cache Autopkg Pkg
      uses: actions/cache@v3
      id: autopkg-pkg-cache
      with:
        path: ${{ github.workspace }}/autopkg.pkg
        key: ${{ runner.os }}-autopkg-pkg-${{ vars.AUTOPKG_VERSION }}

#    - name: Download artifact
#      id: download-artifact
#      uses: dawidd6/action-download-artifact@v2
#      with:
#        check_artifacts: true
#        name: 'autopkg-repo'
#        path: ${{ github.workspace }}/output/
#        if_no_artifact_found: ignore

    - name: Cache Repos
      uses: actions/cache@v3
      id: repos-cache
      with:
        path: ${{ github.workspace }}/repos.tar
        key: ${{ runner.os }}-repos-${{ hashFiles('${{ github.workspace }}/repos.tar') }}

    - name: Decompress repos
      if: steps.repos-cache.outputs.cache-hit == 'true'
      run: |
        tar -xvf "$GITHUB_WORKSPACE"/repos.tar -C /

    - name: Download Munki
      if: steps.munki-pkg-cache.outputs.cache-hit != 'true'
      run: |
        curl -L https://github.com/munki/munki/releases/download/v${{ vars.MUNKI_VERSION }}/munkitools-${{ vars.MUNKI_EXPLICIT_VERSION }}.pkg --output ${{ github.workspace }}/munkitools.pkg

    - name: Download AutoPkg
      if: steps.autopkg-pkg-cache.outputs.cache-hit != 'true'
      run: |
        curl -L https://github.com/autopkg/autopkg/releases/download/v${{ vars.AUTOPKG_VERSION }}/autopkg-${{ vars.AUTOPKG_VERSION }}.pkg --output ${{ github.workspace }}/autopkg.pkg

    - name: Install Munki and AutoPkg
      run: |
        sudo installer -pkg ${{ github.workspace }}/munkitools.pkg -target /
        sudo installer -pkg ${{ github.workspace }}/autopkg.pkg -target /

    - name: Checkout your Munki LFS repo
      uses: actions/checkout@v3
      with:
        repository: joncrain/munki_repo
        token: ${{ secrets.MUNKI_GITHUB_TOKEN }}
        fetch-depth: 1
        ref: refs/heads/main
        path: munki_repo

    - name: Configure AutoPkg
      if: steps.repos-cache.outputs.cache-hit != 'true'
      run: |
        defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "$GITHUB_WORKSPACE"/overrides/
        defaults write com.github.autopkg RECIPE_REPO_DIR "$GITHUB_WORKSPACE"/repos/
        defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool YES
        defaults write com.github.autopkg MUNKI_REPO "$GITHUB_WORKSPACE"/munki_repo
        defaults write com.github.autopkg GITHUB_TOKEN "${{ secrets.MUNKI_GITHUB_TOKEN }}"
        git config --global user.name "runner"
        git config --global user.email "runner@githubactions.local"

    - name: Configure AutoPkg Repos
      if: steps.repos-cache.outputs.cache-hit != 'true'
      run: |
        for repo in $(cat repo_list.txt); do autopkg repo-add "$repo"; done

    - name: Update AutoPkg Repos
      if: steps.repos-cache.outputs.cache-hit == 'true'
      run: autopkg repo-update all

    - name: Run makecatalogs
      run: /usr/local/munki/makecatalogs munki_repo

    - name: Run AutoPkg
      run: |
        pip3 install requests
        python3 autopkg_tools.py -l recipe_list.json
        if [ -f pull_request_title ]; then
        echo "TITLE=$(cat pull_request_title)" >> $GITHUB_ENV
        echo "BODY<<EOF" >> $GITHUB_ENV
        cat pull_request_body >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        fi
      env:
        RECIPE: ${{ github.event.inputs.recipe }}
        SLACK_WEBHOOK_TOKEN: ${{ secrets.autopkg_slack_token }}

    - name: Compress repos
      run: |
        tar -cvf ${{ github.workspace }}/repos.tar "$GITHUB_WORKSPACE"/repos/ /Users/runner/Library/Preferences/com.github.autopkg.plist

#    - name: Upload Autopkg files as artifact
#      uses: actions/upload-artifact@v3
#      if: env.REPO_CHECKSUM != env.NEW_REPO_CHECKSUM
#      with:
#        name: autopkg-repo
#        path: ${{ github.workspace }}/repos.tar
#        retention-days: 14

    - name: Create Trust Info pull request
      if: env.TITLE
      run: |
        export BRANCH_NAME=trust-info-`date +'%Y-%m-%d'`
        git checkout -b $BRANCH_NAME
        git add overrides/
        git commit -m "${{ env.TITLE }}"
        git push --set-upstream origin $BRANCH_NAME
        jq -n --arg title "${{ env.TITLE }}" \
              --arg body "$BODY" \
              --arg head "$BRANCH_NAME" \
           '{title: $title, body: $body, head: $head, "base": "${{ github.ref }}"}' | curl -s --request POST \
           --url https://api.github.com/repos/${{ github.repository }}/pulls \
           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
           --header 'content-type: application/json' \
           -d@-
