name: AutoPkg run

on:
  workflow_dispatch: # manually triggered
    inputs:
      recipe:
        description: Recipe to Run (optional)
        required: false

jobs:
  AutoPkg:
    strategy:
        matrix:
          target:  ["Firefox.munki", "test-munki-pkg.munki"]
    uses: joncrain/autopkg-ci/.github/workflows/reusable_autopkg.yml@main
    with:
      recipe_override: ${{ matrix.target }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MUNKI_GITHUB_TOKEN: ${{ secrets.MUNKI_GITHUB_TOKEN }}
