name: Multi AutoPkg run

on:
  workflow_dispatch: # manually triggered
    inputs:
      recipe:
        description: Recipe to Run (optional)
        required: false

jobs:
  AutoPkg:
    strategy:
        matrix:
          target:  ["Firefox.munki", "GoogleChrome.munki", "Cyberduck.munki", "AdobeReader.munki", "MicrosoftEdge.munki", "Spotify.munki"]
    uses: joncrain/autopkg-ci/.github/workflows/reusable_autopkg.yml@main
    with:
      recipe_override: ${{ matrix.target }}
    secrets: inherit
