name: Reusable AutoPkg

on:
  workflow_call:
    inputs:
      recipe_override:
        required: false
        type: string
    secrets:
      MUNKI_GITHUB_TOKEN:
        required: true
      autopkg_slack_token:
        required: false

jobs:
  AutoPkg:
    runs-on: macos-latest
    timeout-minutes: 10 # Keeps your builds from running too long
    steps:
    - name: Checkout AutoPkg recipes (this repo)
      uses: actions/checkout@v3

    - name: Download Munki
      run: |
        curl -L https://github.com/munki/munki/releases/download/v${{ vars.MUNKI_VERSION }}/munkitools-${{ vars.MUNKI_EXPLICIT_VERSION }}.pkg --output ${{ github.workspace }}/munkitools.pkg

    - name: Download AutoPkg
      run: |
        curl -L https://github.com/autopkg/autopkg/releases/download/v${{ vars.AUTOPKG_VERSION }}/autopkg-${{ vars.AUTOPKG_VERSION }}.pkg --output ${{ github.workspace }}/autopkg.pkg

    - name: Install Munki and AutoPkg
      run: |
        sudo installer -pkg ./munkitools.pkg -target /
        sudo installer -pkg ./autopkg.pkg -target /

    - name: Checkout your Munki LFS repo
      uses: actions/checkout@v3
      with:
        repository: joncrain/munki_repo
        token: ${{ secrets.MUNKI_GITHUB_TOKEN }}
        fetch-depth: 1
        ref: refs/heads/main
        path: munki_repo

    - name: Configure AutoPkg
      run: |
        defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "$GITHUB_WORKSPACE"/overrides/
        defaults write com.github.autopkg RECIPE_REPO_DIR "$GITHUB_WORKSPACE"/repos/
        defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool YES
        defaults write com.github.autopkg MUNKI_REPO "$GITHUB_WORKSPACE"/munki_repo
        defaults write com.github.autopkg GITHUB_TOKEN "${{ secrets.MUNKI_GITHUB_TOKEN }}"
        git config --global user.name "runner"
        git config --global user.email "runner@githubactions.local"

    - name: Configure AutoPkg Repos
      run: |
        for repo in $(cat repo_list.txt); do autopkg repo-add "$repo"; done

    - name: Run makecatalogs
      run: /usr/local/munki/makecatalogs munki_repo

    - name: Run AutoPkg
      run: |
        # login to gh cli
        pip3 install -r requirements.txt
        python3 autopkg_tools.py -l recipe_list.json
      env:
        RECIPE: ${{ inputs.recipe_override }}
        SLACK_WEBHOOK_TOKEN: ${{ secrets.autopkg_slack_token }}
        MUNKI_GITHUB_TOKEN: ${{ secrets.MUNKI_GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}